// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    app_costs_daily: {
        name: "app_costs_daily";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          app_name: string;
          /** @sqlType STRING */
          usage_date: string;
          /** @sqlType DOUBLE */
          dbus: number;
        }>;
      };
    app_costs_summary: {
        name: "app_costs_summary";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          app_name: string;
          /** @sqlType DOUBLE */
          total_dbus: number;
          /** @sqlType DOUBLE */
          avg_dbus_per_day: number;
          /** @sqlType STRING */
          first_seen: string;
          /** @sqlType STRING */
          last_seen: string;
        }>;
      };
    app_daily_actions: {
        name: "app_daily_actions";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType DATE */
          event_date: string;
          /** @sqlType STRING */
          action: string;
          /** @sqlType BIGINT */
          event_count: number;
        }>;
      };
    app_schedule: {
        name: "app_schedule";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          app_name: string;
          /** @sqlType BOOLEAN */
          always_on: boolean;
          /** @sqlType INT */
          idle_threshold_minutes: number;
          /** @sqlType INT */
          force_stop_hour: number;
          /** @sqlType STRING */
          notes: string;
          /** @sqlType TIMESTAMP */
          updated_at: string;
        }>;
      };
    events_by_action: {
        name: "events_by_action";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          action: string;
          /** @sqlType BIGINT */
          event_count: number;
        }>;
      };
    recent_events: {
        name: "recent_events";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType TIMESTAMP */
          event_time: string;
          /** @sqlType STRING */
          app_name: string;
          /** @sqlType STRING */
          creator: string;
          /** @sqlType STRING */
          action: string;
          /** @sqlType STRING */
          reason: string;
          /** @sqlType BIGINT */
          traffic_count: number;
          /** @sqlType INT */
          idle_threshold_minutes: number;
          /** @sqlType DOUBLE */
          uptime_hours: number;
          /** @sqlType STRING */
          compute_state: string;
          /** @sqlType BOOLEAN */
          dry_run: boolean;
        }>;
      };
  }
}
